name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff
        run: curl -L get.huff.sh | bash -s -- -y \
              && source /home/runner/.bashrc \
              && huffup -b stage

      - name: Install Dependencies
        run: forge install
      - name: Update Modules
        run: forge update
      - name: Run lints
        run: forge build
      - name: Run Tests
        run: forge test
