name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff
        uses: huff-language/huff-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install
      - name: Update Modules
        run: forge update
      - name: Run lints
        run: forge build
      - name: Run Tests
        run: forge test
